blank_issues_enabled: false
contact_links:
  - name: Haz tus Preguntas
    url: https://github.com/nikosantis/propuesta-nueva-constitucion-chile/discussions
    about: Haz preguntas y discute con otros miembros
